import numpy as np
print("Creating an array of random values")
a=np.random.random((5,3))
print(a)
print("Finding the max value of the array")
print(a.max())
print("Finding the min value of the array")
print(a.min())
print("Finding the sum of the rows of array")
print(a.sum(axis=1))
print("Finding the sum of the columns of array")
print(a.sum(axis=0))
print("Sum of array")
print(a.sum())
